
## Exercice 3

==========================================================================

## Diamonds

```{r}

library(ggplot2)

data(diamonds)

summary(diamonds)

?diamonds

```

## Price Histogram

```{r}

qplot(x=price, data=diamonds)

```

## Price Histogram Summary

```{r}

qplot(x=price, data=diamonds, binwidth=30)

summary(diamonds$price)

```

## Diamond Counts

```{r}

l500 <- NA
l500 <- ifelse(diamonds$price<500,1,0)

l500 <- factor(l500)

sum(l500 == 1)


```

```{r}

l250 <- NA
l250 <- ifelse(diamonds$price<250,1,0)

l250 <- factor(l250)

sum(l250 == 1)


```

```{r}

l15000 <- NA
l15000 <- ifelse(diamonds$price>=15000,1,0)

l15000 <- factor(l15000)

sum(l15000 == 1)

```

## Cheaper Diamonds

```{r}
qplot(x=price, data=diamonds, binwidth=30) +
  scale_x_continuous(limits=c(0,2000))

```

```{r}
qplot(x=price, data=diamonds, binwidth=1) +
  scale_x_continuous(limits=c(500,750))

```

```{r}
qplot(x=price, data=diamonds, binwidth=1) +
  scale_x_continuous(limits=c(550,650))

```

## Price by Cut Histograms

```{r}

qplot(x=price, data=diamonds, binwidth=30) +
  facet_wrap(~cut, ncol=3)


```

## Price by Cut
```{r}

by(diamonds$price, diamonds$cut,max)

```
```{r}

by(diamonds$price, diamonds$cut,min)

```
```{r}

by(diamonds$price, diamonds$cut,median)

```

```{r}

by(diamonds$price, diamonds$cut,summary)

```

## Scales and Multiple Histograms

```{r}

qplot(x = price, data = diamonds) + facet_wrap(~cut, scales="free")

```

## Price per Carat by Cut

```{r}

names(diamonds)
summary(diamonds$carat)

qplot(x = price/carat, data = diamonds) + facet_wrap(~cut, scales="free") +
  scale_x_log10()

```

## Price Box Plots

```{r}

qplot(x=color, y=price, data = diamonds,
      geom='boxplot') +
  coord_cartesian(ylim=c(0,10000))

ggsave('boxplots_color.png')

```

```{r}

qplot(x=clarity, y=price, data = diamonds,
      geom='boxplot') +
  coord_cartesian(ylim=c(0,7000))

ggsave('boxplots_clarity.png')

```

## Interquartile Range - IQR

```{r}

by(diamonds$price,diamonds$color, summary)

```

```{r}

by(diamonds$price,diamonds$color, mean)

```


```{r}

?diamonds

by(diamonds$price,diamonds$color, IQR)

```

## Price per Carat Box Plot

```{r}

qplot(x=color, y=price/carat, data = diamonds,
      geom='boxplot') +
  coord_cartesian(ylim=c(2000,6000))

ggsave('boxplot price_carat.png')

```

## Carat Frecuency Polygon

```{r}
qplot(x = carat,
      data = diamonds,
      binwidth = 0.1,
      geom = 'freqpoly') +
  scale_x_continuous(limits=c(0,2), breaks = seq(0,2,0.2))

```






