Exercice 4

===========================================================

## Price vs x

```{r}

library(ggplot2)

data(diamonds)

summary(diamonds)

```

```{r}

ggplot(aes(x=x, y=price), data=diamonds) + 
  geom_point()

```

## Correlations

```{r}

with(diamonds,cor.test(x,price, method = 'pearson'))

with(diamonds,cor.test(y,price, method = 'pearson'))

with(diamonds,cor.test(z,price, method = 'pearson'))

```

## Price vs Depth

```{r}

ggplot(aes(x=depth, y=price), data=diamonds) + 
  geom_point() 

```

## Ajustments Price vs Depth


```{r}

ggplot(aes(x=depth, y=price), data=diamonds) + 
  geom_point(alpha=1/100) +
  scale_x_continuous(breaks=seq(0,80,2))

```

## Correlation - Price vs Depth

```{r}

with(diamonds,cor.test(depth,price, method = 'pearson'))


```

## Price vs Carat


```{r}

ggplot(aes(x = carat, y = price), data = diamonds) + 
  geom_point() + 
  xlim(0, quantile(diamonds$carat, 0.99)) +
  ylim(0, quantile(diamonds$price, 0.99))

```

## Privce vs Volume

```{r}

ggplot(aes(x=x*y*z, y=price), data=diamonds) + 
  geom_point()

```


```{r}

library(plyr)

diamonds$volume= diamonds$x*diamonds$y*diamonds$z

ggplot(aes(x=volume, y=price), data=diamonds) + 
  geom_point()

count(diamonds$volume == 0)

detach("package:plyr", unload=TRUE)

```

## Correlation on subsets

```{r}

with(diamonds,cor.test(volume,price, method = 'pearson'))

diamonds$volume_ok <- diamonds$volume > 0 & diamonds$volume < 800


with(subset(diamonds,diamonds$volume_ok ),cor.test(volume,price, method = 'pearson'))


```

## Adjustments - Price vs Volume

```{r}

ggplot(aes(x=volume, y=price), data=subset(diamonds,diamonds$volume_ok) ) +
  geom_point() +
  geom_smooth(method = 'lm', color = 'red')

```

## Mean Price by Clarity

```{r}

diamondsByClarity<- diamonds %>%
  group_by(clarity) %>%
  summarise(mean_price=mean(price),
          median_price = median(price),
          min_price = min(price),
          max_price = max(price),
          n= n()) %>%
  arrange(clarity)

```

## Barcharts of Mean Price

```{r}

data(diamonds)
library(dplyr)

diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

```


```{r}

library(gridExtra)

bp1 <- barplot(diamonds_mp_by_clarity$mean_price, names.arg=diamonds_mp_by_clarity$clarity, horiz=TRUE, border=NA, las=1, main="Mean price by Clarity")

bp2 <- barplot(diamonds_mp_by_color$mean_price, names.arg=diamonds_mp_by_color$color, horiz=TRUE, border=NA, las=1, main="Mean price by Color")


grid.arrange(bp1,bp2,ncol=1)

```
