Exercice 5

==========================================================================

#Price Histogram with Facet and Color


```{r Import Diamonds Dataset}

library(ggplot2)

data(diamonds)

summary(diamonds)

```


```{r Price Histogram with Facet and Color}

ggplot(aes(x=log(price)), data=diamonds) +
  geom_histogram(aes(fill=cut)) +
  facet_wrap(~color, ncol=3) +
  scale_fill_brewer(type = 'qual')
  
  

```

#Price vs. Table Colored by Cut

```{r Price vs. Table Colored by Cut}

ggplot(aes(y=price, x=table), data=diamonds) +
  geom_point(alpha=1/5, aes(color=cut)) +
  scale_x_continuous(breaks=seq(40,80,2))+
  scale_fill_brewer(type = 'qual') 


```

#Tipical table Value

```{r Tipical table Value}

ideal <- subset(diamonds, diamonds$cut=="Ideal")

summary(ideal$table)

```

```{r}

ideal <- subset(diamonds, diamonds$cut=="Premium")

summary(ideal$table)

```

# Price vs. Volume and Diamond Clarity

```{r Price vs. Volume and Diamond Clarity}

ggplot(aes(y=price, x=(x*y*z)), data=diamonds) +
  geom_point(lpha=1/5, aes(color=clarity)) +
  scale_y_log10() +
  coord_cartesian(xlim=c(0,quantile((diamonds$x*diamonds$y*diamonds$z),0.95)))
  scale_fill_brewer(type = 'div') +


```

# Proportion of Frindships Initiated

```{r import dataset}

getwd()
setwd("C:/Users/Usuario/Desktop")

pf <- read.csv('pseudo_facebook.tsv', sep = '\t')

summary(pf)

```

```{r Proportion of Frindships Initiated}

pf <- transform(pf, prop_initiated = ifelse(friend_count == 0, 0,friendships_initiated/friend_count))

summary(pf$prop_initiated)

```

# Prop Initiated vs Tenure

```{r}

pf$year_joined <- floor(2014 - pf$tenure/365)

summary(pf$year_joined)

table(pf$year_joined)

pf$year_joined.bucket <- cut(pf$year_joined,
                             c(2004, 2009, 2011, 2012, 2014))


```

```{r}


ggplot(aes(x=tenure,y=prop_initiated),
       data = subset(pf,tenure>=1)) +
  geom_line(aes(color = year_joined.bucket), 
            stat = 'summary', 
            fun.y= median) 

```


# Smoothing prop_initiated vs. tenure

```{r Smoothing prop_initiated vs. tenure}

ggplot(aes(x=tenure,y=prop_initiated),
       data = subset(pf,tenure>=1)) +
  geom_smooth(aes(color = year_joined.bucket))

```

```{r}

ggplot(aes(x = 90 * round(tenure / 90),y=prop_initiated),
       data = subset(pf,tenure>=1)) +
  geom_line(aes(color = year_joined.bucket), 
            stat = 'summary', 
            fun.y= median) 

```

# Largest Group Mean prop_initiated

```{r Largest Group Mean prop_initiated}

group_max <- subset(pf,pf$year_joined>2012 & pf$year_joined<=2014)

summary(group_max$prop_initiated)

```

# Price/Carat Binned,Faceted, & Colo..

```{r Price/Carat Binned,Faceted, & Colo..}

ggplot(aes(x = cut, y = price/carat), data = diamonds) +
  facet_wrap(~clarity) +
  geom_point(aes(color=color)) +
  scale_color_brewer(type = 'div')

```

```{r}

ggplot(aes(x = cut, y = price/carat), data = diamonds) +
  facet_wrap(~clarity) +
  geom_point(aes(color=color), position="jitter") +
  scale_color_brewer(type = 'div')

```

```{r}

ggplot(aes(x = cut, y = price/carat), data = subset(diamonds,fill = color)) +
  facet_wrap(~clarity) +
  geom_point(aes(color=color), position="jitter") +
  scale_color_brewer(type = 'div')

```
